[package]
name = "api_cloud_entry"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../api" }
domain = { path = "../domain" }

lambda_http = "0.12.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
