[workspace]
resolver = "2"
members = [
    "api",
    "api_cloud_entry",
    "api_local_entry",
    "api_sqs_entry",
    "domain",
    "event_publisher",
    "game_logic",
    "notifier",
    "service",
    "storage",
]
