[package]
name = "lambda_entry"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.12.0"
lambda_lib = { path = "../lambda_lib" }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }

