[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[features]
in_memory = []

[dependencies]
domain = { path = "../domain" }

aws-config = "1.5.4"
aws-sdk-dynamodb = "1.37.0"
aws-smithy-runtime-api = "1.7.1"
tokio = { version = "1", features = ["full"] }
